### PR TITLE
generate epub

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by unknwon** [comment]
感谢提交， 但我觉得没有必要吧，还要装 pandoc。。

**Comment by sysescool** [comment]
@fenglc use pandoc can generate epub from this repo? I notice you have deleted the repo, could you teach me or show me some context about pandoc?

**Comment by ghost** [comment]
@sysescool 
https://github.com/unknwon/the-way-to-go_ZH_CN/blob/badfabee9455384e649d09a97887a7bc6ba5e3ca/build/Makefile

```
cd build
make -f Makefile
```

**Comment by sysescool** [comment]
Thank you, I learn it. I forked it and added the Makefile you write. @fenglc

**Pull request closed without merging**
