### PR TITLE
update "tw-way pipe" to "tow-way pipe"

### PR DESCRIPTION
**Pull request by gomaster-me**
update "tw-way pipe" to "tow-way pipe"

### CODE REVIEW

**Comment by gomaster-me** [comment]
update "tw-way pipe" to "tow-way pipe"

**Comment by Unknwon** [comment]
老哥你还是拼错了，是 `two`。。。

**Comment by gomaster-me** [comment]
update "tw-way pipe" to "two-way pipe"

**Comment by Unknwon** [comment]
6666

**Pull request merged**
