### PR TITLE
fix missing img 20.8_fig20.1.png and url format in 20.8.md

### PR DESCRIPTION
**Pull request by sysescool**
There is a problem with the markdown rendering here.
An image is missing.

image

### CODE REVIEW

**Comment by sysescool** [comment]
BTW, @unknwon is it your website: https://go.timpaik.top/ ? The Chapter 20 and 21 is unreadable.

**Comment by sysescool** [comment]
@unknown please delete this closed pull&request. thank you.

**Comment by sysescool** [comment]
@unknwon please delete this closed pull&request. thank you.

**Comment by unknwon** [comment]
Hmm, there is no option to delete a PR on GitHub.com. 🤔

**Comment by sysescool** [comment]
@unknwon  Sorry for taking up your time, please fill out the following https://support.github.com/contact/private-information according to https://docs.github.com/en/site-policy/content-removal-policies/github-private-information-removal-policy. Then the pull request link can be removed.
Sincerely apologize for taking up your time again.

**Pull request closed without merging**
