### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by songjiayang**
根据上下文，此处该变量应该是 `shortUrl ` 而不是 `shwortUrl `

### CODE REVIEW

**Comment by appleboy** [comment]
Nothing to change?

**Comment by songjiayang** [comment]
@appleboy 
https://github.com/Unknwon/the-way-to-go_ZH_CN/pull/256/files?short_path=99b1e7b#diff-99b1e7b5d5c06a0da4c28baca4f6ef21

**Comment by appleboy** [comment]
@songjiayang I can't see the detail information from `Files Changed` tab

https://github.com/Unknwon/the-way-to-go_ZH_CN/pull/256/files

**Comment by songjiayang** [comment]
hi @appleboy, would you mind tell me what's text editor you use, atom I used. 
I can't see the changes in `First Tab`  but can see it in `Second Tab ` **Display the rich diff**

**Comment by appleboy** [comment]
screen shot 2016-04-27 at 10 17 35 am

**Comment by songjiayang** [comment]
I got it , fix soon, thanks.
The reason is my editor trim the line last space automatically.

**Comment by songjiayang** [comment]
Hi @appleboy ,  when I made a small change in in file `09.11.md` but git diff content looks like:

screen shot 2016-04-28 at 2 40 15 pm

what's wrong, do you have some idea? I guess there are some different line-ending-selectors.

see the link https://github.com/atom/line-ending-selector

**Comment by appleboy** [comment]
@songjiayang You can edit document online using Github web editor.

**Comment by songjiayang** [comment]
@appleboy the same result.
It only works rich diff.
screen shot 2016-04-28 at 3 01 14 pm

**Comment by songjiayang** [comment]
I guess someone edited it on WINDOWS.

**Pull request closed without merging**
